/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Farmacia;

import javax.swing.SwingUtilities;
import ui.FormularioPedido;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new FormularioPedido().setVisible(true));
}

}
